name: bingo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  bloc: ^9.0.0
  change_app_package_name: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

  flutter_layout_grid: ^2.0.7

  freezed_annotation: ^3.0.0
  google_mobile_ads: ^6.0.0
  lottie: ^3.1.2
  shared_preferences: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6


   
    
  

flutter:
  uses-material-design: true
  assets:

    - assets/img/
    - assets/lottie/
    - assets/music/
